name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  http: ^1.6.0
  flutter_secure_storage: ^9.2.4
  public_file_saver: ^1.2.0
  firebase_core: ^2.32.0
  firebase_messaging: ^14.6.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
